[workspace]
members = [
    "rust_interface",
    "examples/node",
]

[patch.crates-io]
sysinfo = { git = "https://github.com/alekseysidorov/sysinfo.git", rev = "0c3905cd09ca28dc459e28d857f34d3f547e728c" }
